/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;
import java.awt.Color;


public class MenuPrincipalTela extends javax.swing.JFrame {
    

    /**
     * Creates new form MenuPrincipalTela
     */
    public MenuPrincipalTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        numUnidade = new javax.swing.JTextField();
        unidade = new javax.swing.JLabel();
        btnSairIcon = new javax.swing.JButton();
        documentacaoBotao = new javax.swing.JLabel();
        selecaoJogadorBotao = new javax.swing.JLabel();
        creditosBotao = new javax.swing.JLabel();
        selecaoUnidadeBotao = new javax.swing.JLabel();
        sairBotao = new javax.swing.JLabel();
        tutorialBotao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(12, 12, 12));

        jPanel1.setBackground(new java.awt.Color(12, 12, 12));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(948, 698));
        jPanel1.setLayout(null);

        numUnidade.setEditable(false);
        numUnidade.setBackground(new java.awt.Color(255, 255, 255));
        numUnidade.setFont(new java.awt.Font("Montserrat", 1, 40)); // NOI18N
        numUnidade.setForeground(new java.awt.Color(85, 51, 141));
        numUnidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numUnidade.setBorder(null);
        numUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numUnidadeActionPerformed(evt);
            }
        });
        jPanel1.add(numUnidade);
        numUnidade.setBounds(880, 20, 50, 70);
        numUnidade.getAccessibleContext().setAccessibleName("");

        unidade.setFont(new java.awt.Font("Montserrat", 1, 40)); // NOI18N
        unidade.setForeground(new java.awt.Color(85, 51, 141));
        unidade.setText("UNIDADE");
        jPanel1.add(unidade);
        unidade.setBounds(670, 20, 210, 70);

        btnSairIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive - Colégio Santa Cruz\\Documentos\\NetBeansProjects\\ProjetoIntegradorS1\\src\\main\\java\\com\\mycompany\\mavenproject1\\Imagens\\closeIcon.png")); // NOI18N
        btnSairIcon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSairIcon.setMaximumSize(new java.awt.Dimension(54, 54));
        btnSairIcon.setMinimumSize(new java.awt.Dimension(54, 54));
        btnSairIcon.setPreferredSize(new java.awt.Dimension(54, 54));
        btnSairIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairIconMouseClicked(evt);
            }
        });
        btnSairIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairIconActionPerformed(evt);
            }
        });
        jPanel1.add(btnSairIcon);
        btnSairIcon.setBounds(30, 30, 54, 54);

        documentacaoBotao.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        documentacaoBotao.setForeground(new java.awt.Color(255, 255, 255));
        documentacaoBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        documentacaoBotao.setText("Documentação");
        documentacaoBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                documentacaoBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                documentacaoBotaoMouseExited(evt);
            }
        });
        jPanel1.add(documentacaoBotao);
        documentacaoBotao.setBounds(50, 320, 840, 80);

        selecaoJogadorBotao.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        selecaoJogadorBotao.setForeground(new java.awt.Color(255, 255, 255));
        selecaoJogadorBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoJogadorBotao.setText("Seleção de Jogador");
        selecaoJogadorBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoJogadorBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selecaoJogadorBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selecaoJogadorBotaoMouseExited(evt);
            }
        });
        jPanel1.add(selecaoJogadorBotao);
        selecaoJogadorBotao.setBounds(50, 240, 840, 80);

        creditosBotao.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        creditosBotao.setForeground(new java.awt.Color(255, 255, 255));
        creditosBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditosBotao.setText("Créditos");
        creditosBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditosBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                creditosBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                creditosBotaoMouseExited(evt);
            }
        });
        jPanel1.add(creditosBotao);
        creditosBotao.setBounds(50, 480, 840, 80);

        selecaoUnidadeBotao.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        selecaoUnidadeBotao.setForeground(new java.awt.Color(255, 255, 255));
        selecaoUnidadeBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoUnidadeBotao.setText("Seleção de Unidades");
        selecaoUnidadeBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotaoMouseExited(evt);
            }
        });
        jPanel1.add(selecaoUnidadeBotao);
        selecaoUnidadeBotao.setBounds(50, 160, 840, 80);

        sairBotao.setBackground(new java.awt.Color(0, 0, 0));
        sairBotao.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        sairBotao.setForeground(new java.awt.Color(255, 255, 255));
        sairBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sairBotao.setText("Sair do Jogo");
        sairBotao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sairBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sairBotaoMouseExited(evt);
            }
        });
        jPanel1.add(sairBotao);
        sairBotao.setBounds(50, 560, 840, 80);

        tutorialBotao.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        tutorialBotao.setForeground(new java.awt.Color(255, 255, 255));
        tutorialBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tutorialBotao.setText("Tutorial");
        tutorialBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tutorialBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tutorialBotaoMouseExited(evt);
            }
        });
        jPanel1.add(tutorialBotao);
        tutorialBotao.setBounds(50, 400, 840, 80);

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BD ACADEMY");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 0, 300, 106);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive - Colégio Santa Cruz\\Documentos\\NetBeansProjects\\ProjetoIntegradorS1\\src\\main\\java\\com\\mycompany\\mavenproject1\\Imagens\\topo.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(570, -50, 470, 210);

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jSeparator1.setMinimumSize(new java.awt.Dimension(948, 20));
        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 5));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 0, 950, 110);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairIconActionPerformed

    private void btnSairIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairIconMouseClicked
        setVisible(false);
        new PressEnterTela().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairIconMouseClicked

    private void sairBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairBotaoMouseExited
        sairBotao.setForeground(Color.white);
    }//GEN-LAST:event_sairBotaoMouseExited

    private void sairBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairBotaoMouseEntered
        sairBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_sairBotaoMouseEntered

    private void sairBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairBotaoMouseClicked

        System.exit(0);
    }//GEN-LAST:event_sairBotaoMouseClicked

    private void tutorialBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorialBotaoMouseExited
        tutorialBotao.setForeground(Color.white);
    }//GEN-LAST:event_tutorialBotaoMouseExited

    private void tutorialBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorialBotaoMouseEntered
        tutorialBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_tutorialBotaoMouseEntered

    private void documentacaoBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documentacaoBotaoMouseExited
        documentacaoBotao.setForeground(Color.white);
    }//GEN-LAST:event_documentacaoBotaoMouseExited

    private void documentacaoBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documentacaoBotaoMouseEntered
        documentacaoBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_documentacaoBotaoMouseEntered

    private void selecaoJogadorBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoJogadorBotaoMouseExited
        selecaoJogadorBotao.setForeground(Color.white);
    }//GEN-LAST:event_selecaoJogadorBotaoMouseExited

    private void selecaoJogadorBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoJogadorBotaoMouseEntered
        selecaoJogadorBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_selecaoJogadorBotaoMouseEntered

    private void selecaoJogadorBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoJogadorBotaoMouseClicked
        setVisible(false);
        new EscolhaJogadorTela().setVisible(true);
    }//GEN-LAST:event_selecaoJogadorBotaoMouseClicked

    private void selecaoUnidadeBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotaoMouseExited
        selecaoUnidadeBotao.setForeground(Color.white);
    }//GEN-LAST:event_selecaoUnidadeBotaoMouseExited

    private void selecaoUnidadeBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotaoMouseEntered
        selecaoUnidadeBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_selecaoUnidadeBotaoMouseEntered

    private void selecaoUnidadeBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotaoMouseClicked
        setVisible(false);
        new EscolhaUnidadesTela().setVisible(true);
    }//GEN-LAST:event_selecaoUnidadeBotaoMouseClicked

    private void creditosBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditosBotaoMouseExited
        creditosBotao.setForeground(Color.white);
    }//GEN-LAST:event_creditosBotaoMouseExited

    private void creditosBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditosBotaoMouseEntered
        creditosBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_creditosBotaoMouseEntered

    private void creditosBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditosBotaoMouseClicked
        setVisible(false);
        new CreditosTelaV2().setVisible(true);
    }//GEN-LAST:event_creditosBotaoMouseClicked

    private void numUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numUnidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSairIcon;
    private javax.swing.JLabel creditosBotao;
    private javax.swing.JLabel documentacaoBotao;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField numUnidade;
    private javax.swing.JLabel sairBotao;
    private javax.swing.JLabel selecaoJogadorBotao;
    private javax.swing.JLabel selecaoUnidadeBotao;
    private javax.swing.JLabel tutorialBotao;
    private javax.swing.JLabel unidade;
    // End of variables declaration//GEN-END:variables
}
